version: "3.3"

services:
  moltools-server:
    build:
      context: . 
      dockerfile: Dockerfile.server
    image: moltools-server
    restart: always
    networks:
      - moltools-network

  moltools-client:
    build: 
      context: . 
      dockerfile: Dockerfile.client 
    image: moltools-client
    ports:
      - "4001:80"
    restart: always
    networks:
      - moltools-network

networks:
  moltools-network:
    driver: bridge
