# This Dockerfile builds API only
FROM python:3.10 
WORKDIR /app 
COPY ./src/server/ ./
RUN pip install -r ./requirements.txt 
ENV FLASK_ENV production 
EXPOSE 4000
CMD ["sh", "-c", "gunicorn -b :4000 api:app"]