version: "3.3"
services:
  api:
    build:
      context: . 
      dockerfile: Dockerfile.server
    image: moltools-server
    environment:
      - "SERVER_PORT=${SERVER_PORT}"
    restart: always
    networks:
      - moltools-network
  client:
    build: 
      context: . 
      dockerfile: Dockerfile.client 
      args:
        - SERVER_PORT=${SERVER_PORT}
    image: moltools-client
    ports:
      - "${CLIENT_PORT}:80"
    restart: always
    networks:
      - moltools-network
  database:
    build:
      context: . 
      dockerfile: Dockerfile.database
    image: neo4j:5.16.0
    environment:
      - NEO4J_AUTH=none
    ports:
      - "${BROWSER_PORT}:7474"
      - "${DATABASE_PORT}:7687"
    # volumes:
    #   - /Users/davidmeijer/Desktop/neo4j-data:/data
    restart: always
    networks:
      - moltools-network

networks:
  moltools-network:
    driver: bridge
